# Generated by Django 5.1.6 on 2025-03-26 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_alter_companyprofile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mongo_room_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_id_1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company1', to='companies.companyprofile')),
                ('company_id_2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='company2', to='companies.companyprofile')),
            ],
            options={
                'unique_together': {('company_id_1', 'company_id_2')},
            },
        ),
    ]
