# Generated by Django 5.1.6 on 2025-04-03 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        ('companies', '0007_alter_companyprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='company_id_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company1', to='companies.companyprofile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='company_id_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company2', to='companies.companyprofile'),
        ),
        migrations.AlterField(
            model_name='chatroom',
            name='mongo_room_id',
            field=models.CharField(help_text='MongoDB Room ObjectId or key', max_length=255, unique=True),
        ),
    ]
