services:
  django:
    build: .
    container_name: bravo_django
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
      - static_volume:/app/staticfiles
    restart: always
    stdin_open: true
    tty: true
    command: ["sh", "./entrypoint.sh"]

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file: .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      retries: 10 # Increased retries
      timeout: 5s
      start_period: 20s # Wait before the first check
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    user: celeryuser
    depends_on:
      - redis
      - django
    command: celery -A UA_13XX_bravo worker --loglevel=info
    volumes:
      - .:/app

volumes:
  postgres_data:
  static_volume:
  pgadmin_data:
  redis:
  celery_worker:
