# Generated by Django 5.1.6 on 2025-04-03 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0002_subscription_project_and_more'),
        ('projects', '0002_alter_project_company_alter_project_raised_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='projects.project'),
        ),
    ]
