# Generated by Django 5.1.6 on 2025-04-03 12:01

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_alter_subscription_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='investment_share',
            field=models.DecimalField(decimal_places=3, help_text='Percentage of total investment (e.g., 25.500 for 25.5%)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001')), django.core.validators.MaxValueValidator(Decimal('100.000'))]),
        ),
    ]
