# Generated by Django 5.1.6 on 2025-03-24 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyfollowers'),
        ('companies', '0002_companyprofile_company_size_companyprofile_industry_and_more'),
    ]

    operations = [
    ]
