# Generated by Django 5.1.6 on 2025-03-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyprofile_company_size_companyprofile_industry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='startup_logo',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('startup', 'Startup'), ('enterprise', 'Enterprise'), ('nonprofit', 'Non-Profit')], default='', max_length=255, null=True),
        ),
    ]
