# Generated by Django 5.1.6 on 2025-03-20 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyprofile_startup_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='required_funding',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
