# Generated by Django 5.1.6 on 2025-03-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_companyprofile_required_funding'),
        ('companies', '0004_alter_companyprofile_type'),
    ]

    operations = [
    ]
