# Generated by Django 5.1.6 on 2025-03-28 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_merge_20250324_1202'),
        ('companies', '0004_alter_companyprofile_required_funding'),
    ]

    operations = [
    ]
