# Generated by Django 5.1.6 on 2025-03-25 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_companyfollowers'),
        ('companies', '0002_startupviewhistory'),
        ('companies', '0004_alter_companyprofile_required_funding'),
    ]

    operations = [
    ]
