# Generated by Django 5.1.6 on 2025-03-31 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_merge_20250326_1839'),
        ('companies', '0005_merge_20250328_1436'),
    ]

    operations = [
    ]
