# Generated by Django 5.1.6 on 2025-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_merge_20250331_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='type',
            field=models.CharField(blank=True, choices=[('startup', 'Startup'), ('enterprise', 'Enterprise'), ('nonprofit', 'Non-Profit')], max_length=255, null=True),
        ),
    ]
