# Generated by Django 5.1.6 on 2025-03-29 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_alter_companyprofile_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='startupviewhistory',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='startupviewhistory',
            index=models.Index(fields=['user', 'company'], name='companies_s_user_id_05088e_idx'),
        ),
        migrations.AddIndex(
            model_name='startupviewhistory',
            index=models.Index(fields=['viewed_at'], name='companies_s_viewed__bc0b12_idx'),
        ),
    ]
