# Generated by Django 5.1.6 on 2025-03-31 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationpreference',
            options={'verbose_name_plural': 'User to Company'},
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='notificationpreference',
            unique_together={('user', 'type')},
        ),
    ]
